"""add_responsible_person_and_asset_movement

Revision ID: e40298fabfa0
Revises: f28b26f13e3a
Create Date: 2025-05-11 01:07:19.538601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40298fabfa0'
down_revision: Union[str, None] = 'db7843fc09f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('responsible_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('personnel_number', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personnel_number')
    )
    op.create_index(op.f('ix_responsible_persons_id'), 'responsible_persons', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('inventory_number', sa.String(length=50), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('responsible_person_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['responsible_person_id'], ['responsible_persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_number', name='uq_assets_inventory_number')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_inventory_number'), 'assets', ['inventory_number'], unique=True)
    op.create_table('asset_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('operation_type', sa.Enum('RECEIPT', 'TRANSFER', 'WRITE_OFF', 'SALE', name='operationtype'), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('document_base', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_movements_id'), 'asset_movements', ['id'], unique=False)
    op.create_table('depreciations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('depreciation_method', sa.Enum('LINEAR', 'NONLINEAR', 'PRODUCTION', name='depreciationmethod'), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depreciations_id'), 'depreciations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_depreciations_id'), table_name='depreciations')
    op.drop_table('depreciations')
    op.drop_index(op.f('ix_asset_movements_id'), table_name='asset_movements')
    op.drop_table('asset_movements')
    op.drop_index(op.f('ix_assets_inventory_number'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_responsible_persons_id'), table_name='responsible_persons')
    op.drop_table('responsible_persons')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
